services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
# build
  - echo '-- Start build docker --'
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy

# tagging
  - echo '-- Start tagging docker images --'
  - docker tag udagram-api-feed gigoquan/udagram-api-feed:v1
  - docker tag udagram-api-user gigoquan/udagram-api-user:v1
  - docker tag udagram-frontend gigoquan/udagram-frontend:v1
  - docker tag reverseproxy gigoquan/reverseproxy:v1

after_success:
# loggin
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 
# push
  - docker push gigoquan/udagram-api-feed:v1
  - docker push gigoquan/udagram-api-user:v1
  - docker push gigoquan/udagram-frontend:v1
  - docker push gigoquan/reverseproxy:v1